/**
 * Generated by Antonio Mark (anux.linux@gmail.com)
 */
package sbb.helper.date;

import javax.swing.event.ChangeEvent;

/**
 * @author Antonio Mark
 *
 */
public interface DateChangeListener {

    public void dateChanged(ChangeEvent ce);

}
