/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbb.gui;

import java.awt.BorderLayout;
import java.awt.Container;

import javax.swing.JFrame;
import javax.swing.event.ChangeEvent;

import sbb.helper.I18NHelper;
import sbb.helper.date.DateChangeListener;
import sbb.helper.date.DateHelper;

/**
 *
 * @author Antonio
 */
public class MainFrame extends JFrame implements DateChangeListener {

    private final I18NHelper i18n;
    private final DateHelper dataHelper;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws InstantiationException {
	this.i18n = I18NHelper.getInstance();
	this.dataHelper = DateHelper.getDateHelperInstance();
	this.dataHelper.addDateChangeListener(this);
	initComponents();
	createMainPanel();

    }

    private void createMainPanel() throws InstantiationException {
	MainPanel mainPanel = new MainPanel();
	Container mainContainer = this.getContentPane();
	mainContainer.add(mainPanel, BorderLayout.CENTER);
	updateTitel();
	this.setSize(1200, 600);
	// pack();
    }

    private void updateTitel() {
	int year = dataHelper.getCurrentYear();
	int currentMonth = dataHelper.getCurrentMonth();
	String month = this.i18n.getStringResource("global.month." + currentMonth);
	this.setTitle("Predigtplaner " + month + " " + year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	menueBar = new javax.swing.JMenuBar();
	fileMenu = new javax.swing.JMenu();
	editMenu = new javax.swing.JMenu();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setName("Predigplaner"); // NOI18N

	fileMenu.setText(this.i18n.getStringResource("MainFrame.fileMenu"));
	menueBar.add(fileMenu);

	editMenu.setText(this.i18n.getStringResource("MainFrame.editMenu"));
	menueBar.add(editMenu);

	setJMenuBar(menueBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menueBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dateChanged(ChangeEvent ce) {
	updateTitel();

    }
}
