/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbb.gui;

import javax.swing.JPanel;
import java.awt.*;
import javax.swing.BoxLayout;

/**
 *
 * @author Antonio
 */
public class MainPanel extends JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        createTabs();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private JPanel createCalendarPanel(){
        JPanel calendarPanel = new PlanerPanel();
        calendarPanel.setLayout(new BoxLayout(calendarPanel, BoxLayout.PAGE_AXIS));
        return calendarPanel;
    }
    
    private JPanel createPreachersTab(){
        JPanel calendarPanel = new JPanel();
        calendarPanel.setLayout(new BoxLayout(calendarPanel, BoxLayout.PAGE_AXIS));
        return calendarPanel;
    }
    
    
    private void createTabs(){
        
        JPanel calendarPanel = createCalendarPanel();
        JPanel preachersPanel = createPreachersTab();
        
        this.mainTabbedPane.addTab("Planung", calendarPanel);
        this.mainTabbedPane.addTab("Prediger", preachersPanel);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
