/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbb.gui;

import java.awt.BorderLayout;

import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class MainPanel extends JPanel {

    /**
     * Creates new form MainPanel
     * 
     * @throws java.lang.InstantiationException
     */
    public MainPanel() throws InstantiationException {
	initComponents();
	setupPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private JPanel createCalendarPanel() throws InstantiationException {
	JPanel planerPanel = new PlanerPanel();

	return planerPanel;
    }

    private JPanel createSettingPanel() throws InstantiationException {
	JPanel settingsPanel = new SettingsPanel();

	return settingsPanel;
    }

    private void setupPanel() throws InstantiationException {

	JPanel calendarPanel = createCalendarPanel();
	JPanel settingsPanel = createSettingPanel();

	this.add(calendarPanel, BorderLayout.CENTER);
	this.add(settingsPanel, BorderLayout.SOUTH);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
