/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbb.gui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BoxLayout;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import sbb.helper.date.DateChangeListener;
import sbb.helper.date.DateHelper;

/**
 *
 * @author Antonio
 */
public class PlanerPanel extends JPanel implements DateChangeListener {

    private final DateHelper dateHelper;
    // private JScrollPane calendarScrollPane;

    /**
     * Creates new form PlanerPanel
     */
    public PlanerPanel() throws InstantiationException {
	this.dateHelper = DateHelper.getDateHelperInstance();
	this.dateHelper.addDateChangeListener(this);
	this.initPanel();
	this.setOpaque(true);

    }

    private void initPanel() throws InstantiationException {
	this.initComponents();
	updatePanel();
    }

    private void updatePanel() throws InstantiationException {
	this.removeAll();
	JTable mainTableCalendar = this.createCalendar();
	JScrollPane calendarScrollPane = createScrollPanel(mainTableCalendar);
	this.add(calendarScrollPane);
	this.updateUI();

    }

    private JScrollPane createScrollPanel(Component component) {
	JScrollPane scrollPane = new JScrollPane(component);
	return scrollPane;
    }

    private JTable createCalendar() throws InstantiationException {
	JTable mainTableCalendar = new JTable();
	mainTableCalendar.setColumnSelectionAllowed(true);
	mainTableCalendar.getColumnModel().getSelectionModel()
		.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);

	this.createTableModel(mainTableCalendar);

	int maxColumns = mainTableCalendar.getColumnCount();
	for (int i = 1; i < maxColumns; i++) {
	    TableColumn column = mainTableCalendar.getColumnModel().getColumn(i);
	    this.setUpCombobox(mainTableCalendar, column);
	}

	this.updateColumnWidth(mainTableCalendar);
	this.createSorter(mainTableCalendar);

	return mainTableCalendar;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
	setLayout(new BoxLayout(this, BoxLayout.LINE_AXIS));
    }

    private void createSorter(JTable table) {

	RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(table.getModel()) {
	    @Override
	    public boolean isSortable(int column) {
		return column < 1;
	    }
	};
	List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
	sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
	sorter.setSortKeys(sortKeys);
	table.setRowSorter(sorter);
    }

    private void createTableModel(JTable table) throws InstantiationException {

	TableModel mainModel = new MyTableModel();
	table.setModel(mainModel);

    }

    private void updateColumnWidth(JTable table) {
	TableColumnModel tcm = table.getColumnModel();
	int colCount = tcm.getColumnCount();

	for (int i = 0; i < colCount; i++) {
	    if (i > 0) {
		// Setting the width of days Columns
		tcm.getColumn(i).setMaxWidth(30);
	    }
	    // Setting the width of the name Column
	    tcm.getColumn(i).setMinWidth(100);

	}
    }

    private void setUpCombobox(JTable table, TableColumn column) {
	// Set up the editor for the sport cells.
	JComboBox<String> comboBox = new JComboBox<String>();

	comboBox.addItem("1");
	comboBox.addItem("2");
	comboBox.addItem("3");
	comboBox.addItem("4");
	comboBox.addItem("1v");
	comboBox.addItem(" ");
	column.setCellEditor(new DefaultCellEditor(comboBox));

	// Set up tool tips for the sport cells.
	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
	renderer.setToolTipText("Mein Tooltip");
	column.setCellRenderer(renderer);
    }

    @Override
    public void dateChanged(ChangeEvent ce) {
	try {
	    updatePanel();
	} catch (InstantiationException ie) {
	}
    }

}
