/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbb.gui;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import sbb.helper.I18NHelper;
import sbb.helper.date.DateHelper;

/**
 *
 * @author Antonio
 */
public class SettingsPanel extends JPanel implements ActionListener, ChangeListener {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JLabel monthLabel;
    private JComboBox<String> monthSelector;
    private JLabel yearLabel;
    private JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables

    private final DateHelper dateHelper;
    private final I18NHelper i18n;

    /**
     * Creates new form SettingsPanel
     * 
     * @throws java.lang.InstantiationException
     */
    public SettingsPanel() throws InstantiationException {
	this.dateHelper = DateHelper.getDateHelperInstance();
	this.i18n = I18NHelper.getInstance();
	initComponents();
	initSelection();

    }

    private SpinnerModel getSpinnerModel() {
	int currentYear = dateHelper.getCurrentYear();
	SpinnerModel model = new SpinnerNumberModel(currentYear, // initial
								 // value
		currentYear - 10, // min
		currentYear + 100, // max
		1); // step

	return model;
    }

    private ComboBoxModel<String> getMonthComboBoxModel() {

	String[] months = i18n.getStringResourceArray("SettingsPanel.months");

	ComboBoxModel<String> monthModel = new DefaultComboBoxModel<>(months);
	return monthModel;
    }

    private void initSelection() {
	this.monthSelector.setSelectedIndex(dateHelper.getCurrentMonth());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	yearLabel = new JLabel();
	yearSpinner = new JSpinner();
	monthLabel = new JLabel();
	monthSelector = new JComboBox<>();
	jSeparator1 = new JSeparator();
	jSeparator2 = new JSeparator();

	FlowLayout flowLayout1 = new FlowLayout(FlowLayout.LEADING);
	flowLayout1.setAlignOnBaseline(true);
	setLayout(flowLayout1);

	yearLabel.setText(i18n.getStringResource("SettingsPanel.yaerLabel"));
	add(yearLabel);

	yearSpinner.setModel(getSpinnerModel());
	JSpinner.NumberEditor editor = new JSpinner.NumberEditor(yearSpinner, "#");
	yearSpinner.setEditor(editor);
	yearSpinner.addChangeListener(this);
	add(yearSpinner);

	monthLabel.setText(i18n.getStringResource("SettingsPanel.monthLabel"));
	add(monthLabel);

	monthSelector.setModel(getMonthComboBoxModel());
	monthSelector.addActionListener(this);
	add(monthSelector);
	add(jSeparator1);
	add(jSeparator2);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent actionEvent) {
	Object sourceObject = actionEvent.getSource();
	if (sourceObject instanceof JComboBox<?>) {
	    JComboBox<String> months = (JComboBox<String>) sourceObject;
	    int selectedMonth = months.getSelectedIndex();
	    dateHelper.setMonth(selectedMonth);
	}
    }

    @Override
    public void stateChanged(ChangeEvent ce) {
	Object sourceObject = ce.getSource();
	if (sourceObject instanceof JSpinner) {
	    JSpinner year = (JSpinner) sourceObject;
	    int selectedYear = (int) year.getValue();
	    dateHelper.setYear(selectedYear);
	}

    }
}
